# Generated by Django 4.2.5 on 2023-09-30 18:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(default='example@uccs.edu', max_length=200, verbose_name='UCCS Email'),
        ),
        migrations.AddField(
            model_name='student',
            name='major',
            field=models.CharField(blank=True, choices=[('CSCI-BS', 'BS in Computer Science'), ('CPEN-BS', 'BS in Computer Engineering'), ('BIGD-BI', 'BI in Game Design and Development'), ('BICS-BI', 'BI in Computer Science'), ('BISC-BI', 'BI in Computer Security'), ('CSCI-BA', 'BA in Computer Science'), ('DASE-BS', 'BS in Data Analytics and Systems Engineering')], max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
        ),
    ]
